# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FresnoDailyNewsGetVerbsStartWith.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&FresnoDailyNewsGetVerbsStartWith.proto\"+\n\x18GetVerbsStartWithRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"*\n\x19GetVerbsStartWithResponse\x12\r\n\x05reply\x18\x01 \x01(\t2p\n FresnoDailyNewsGetVerbsStartWith\x12L\n\x11GetVerbsStartWith\x12\x19.GetVerbsStartWithRequest\x1a\x1a.GetVerbsStartWithResponse\"\x00\x42\x44\n\x17org.fresno.adapter.grpcB\'FresnoDailyNewsGetVerbsStartWithServiceP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FresnoDailyNewsGetVerbsStartWith_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027org.fresno.adapter.grpcB\'FresnoDailyNewsGetVerbsStartWithServiceP\001'
  _globals['_GETVERBSSTARTWITHREQUEST']._serialized_start=42
  _globals['_GETVERBSSTARTWITHREQUEST']._serialized_end=85
  _globals['_GETVERBSSTARTWITHRESPONSE']._serialized_start=87
  _globals['_GETVERBSSTARTWITHRESPONSE']._serialized_end=129
  _globals['_FRESNODAILYNEWSGETVERBSSTARTWITH']._serialized_start=131
  _globals['_FRESNODAILYNEWSGETVERBSSTARTWITH']._serialized_end=243
# @@protoc_insertion_point(module_scope)
