# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FresnoDailyNewsGetVerbs.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x46resnoDailyNewsGetVerbs.proto\"&\n\x13GetVerbFormsRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x14GetVerbFormsResponse\x12\r\n\x05reply\x18\x01 \x01(\t2X\n\x17\x46resnoDailyNewsGetVerbs\x12=\n\x0cGetVerbForms\x12\x14.GetVerbFormsRequest\x1a\x15.GetVerbFormsResponse\"\x00\x42;\n\x17org.fresno.adapter.grpcB\x1e\x46resnoDailyNewsGetVerbsServiceP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FresnoDailyNewsGetVerbs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027org.fresno.adapter.grpcB\036FresnoDailyNewsGetVerbsServiceP\001'
  _globals['_GETVERBFORMSREQUEST']._serialized_start=33
  _globals['_GETVERBFORMSREQUEST']._serialized_end=71
  _globals['_GETVERBFORMSRESPONSE']._serialized_start=73
  _globals['_GETVERBFORMSRESPONSE']._serialized_end=110
  _globals['_FRESNODAILYNEWSGETVERBS']._serialized_start=112
  _globals['_FRESNODAILYNEWSGETVERBS']._serialized_end=200
# @@protoc_insertion_point(module_scope)
