# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FresnoDailyNews.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x46resnoDailyNews.proto\x12\x0f\x66resnodailynews\")\n\x16\x45xtractKeywordsRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x17\x45xtractKeywordsResponse\x12\r\n\x05reply\x18\x01 \x01(\t2x\n\x0f\x46resnoDailyNews\x12\x65\n\x0e\x45xtractKeyword\x12\'.fresnodailynews.ExtractKeywordsRequest\x1a(.fresnodailynews.ExtractKeywordsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FresnoDailyNews_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXTRACTKEYWORDSREQUEST']._serialized_start=42
  _globals['_EXTRACTKEYWORDSREQUEST']._serialized_end=83
  _globals['_EXTRACTKEYWORDSRESPONSE']._serialized_start=85
  _globals['_EXTRACTKEYWORDSRESPONSE']._serialized_end=125
  _globals['_FRESNODAILYNEWS']._serialized_start=127
  _globals['_FRESNODAILYNEWS']._serialized_end=247
# @@protoc_insertion_point(module_scope)
